In [1]:
import numpy as np

In [2]:
x=np.arange(10000000)
%time x*7

Wall time: 76 ms

array([       0,        7,       14, ..., 69999979, 69999986, 69999993])

In [3]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones((2,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [5]:
np.ones((2,7))*2

array([[2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2.]])

In [6]:
l=[7,9,6,5,4,3,2,1]
np.array(l)

array([7, 9, 6, 5, 4, 3, 2, 1])

In [7]:
np.arange(100,1,-1)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2])

In [8]:
np.arange(1,1000,2)

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103,
       105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129,
       131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
       157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181,
       183, 185, 187, 189, 191, 193, 195, 197, 199, 201, 203, 205, 207,
       209, 211, 213, 215, 217, 219, 221, 223, 225, 227, 229, 231, 233,
       235, 237, 239, 241, 243, 245, 247, 249, 251, 253, 255, 257, 259,
       261, 263, 265, 267, 269, 271, 273, 275, 277, 279, 281, 283, 285,
       287, 289, 291, 293, 295, 297, 299, 301, 303, 305, 307, 309, 311,
       313, 315, 317, 319, 321, 323, 325, 327, 329, 331, 333, 335, 337,
       339, 341, 343, 345, 347, 349, 351, 353, 355, 357, 359, 361, 363,
       365, 367, 369, 371, 373, 375, 377, 379, 381, 383, 385, 387, 389,
       391, 393, 395, 397, 399, 401, 403, 405, 407, 409, 411, 413, 415,
       417, 419, 421, 423, 425, 427, 429, 431, 433, 435, 437, 439, 441,
       443, 445, 447, 449, 451, 453, 455, 457, 459, 461, 463, 465, 467,
       469, 471, 473, 475, 477, 479, 481, 483, 485, 487, 489, 491, 493,
       495, 497, 499, 501, 503, 505, 507, 509, 511, 513, 515, 517, 519,
       521, 523, 525, 527, 529, 531, 533, 535, 537, 539, 541, 543, 545,
       547, 549, 551, 553, 555, 557, 559, 561, 563, 565, 567, 569, 571,
       573, 575, 577, 579, 581, 583, 585, 587, 589, 591, 593, 595, 597,
       599, 601, 603, 605, 607, 609, 611, 613, 615, 617, 619, 621, 623,
       625, 627, 629, 631, 633, 635, 637, 639, 641, 643, 645, 647, 649,
       651, 653, 655, 657, 659, 661, 663, 665, 667, 669, 671, 673, 675,
       677, 679, 681, 683, 685, 687, 689, 691, 693, 695, 697, 699, 701,
       703, 705, 707, 709, 711, 713, 715, 717, 719, 721, 723, 725, 727,
       729, 731, 733, 735, 737, 739, 741, 743, 745, 747, 749, 751, 753,
       755, 757, 759, 761, 763, 765, 767, 769, 771, 773, 775, 777, 779,
       781, 783, 785, 787, 789, 791, 793, 795, 797, 799, 801, 803, 805,
       807, 809, 811, 813, 815, 817, 819, 821, 823, 825, 827, 829, 831,
       833, 835, 837, 839, 841, 843, 845, 847, 849, 851, 853, 855, 857,
       859, 861, 863, 865, 867, 869, 871, 873, 875, 877, 879, 881, 883,
       885, 887, 889, 891, 893, 895, 897, 899, 901, 903, 905, 907, 909,
       911, 913, 915, 917, 919, 921, 923, 925, 927, 929, 931, 933, 935,
       937, 939, 941, 943, 945, 947, 949, 951, 953, 955, 957, 959, 961,
       963, 965, 967, 969, 971, 973, 975, 977, 979, 981, 983, 985, 987,
       989, 991, 993, 995, 997, 999])

In [9]:
np.arange(2,1000,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208,
       210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234,
       236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260,
       262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286,
       288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312,
       314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338,
       340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 362, 364,
       366, 368, 370, 372, 374, 376, 378, 380, 382, 384, 386, 388, 390,
       392, 394, 396, 398, 400, 402, 404, 406, 408, 410, 412, 414, 416,
       418, 420, 422, 424, 426, 428, 430, 432, 434, 436, 438, 440, 442,
       444, 446, 448, 450, 452, 454, 456, 458, 460, 462, 464, 466, 468,
       470, 472, 474, 476, 478, 480, 482, 484, 486, 488, 490, 492, 494,
       496, 498, 500, 502, 504, 506, 508, 510, 512, 514, 516, 518, 520,
       522, 524, 526, 528, 530, 532, 534, 536, 538, 540, 542, 544, 546,
       548, 550, 552, 554, 556, 558, 560, 562, 564, 566, 568, 570, 572,
       574, 576, 578, 580, 582, 584, 586, 588, 590, 592, 594, 596, 598,
       600, 602, 604, 606, 608, 610, 612, 614, 616, 618, 620, 622, 624,
       626, 628, 630, 632, 634, 636, 638, 640, 642, 644, 646, 648, 650,
       652, 654, 656, 658, 660, 662, 664, 666, 668, 670, 672, 674, 676,
       678, 680, 682, 684, 686, 688, 690, 692, 694, 696, 698, 700, 702,
       704, 706, 708, 710, 712, 714, 716, 718, 720, 722, 724, 726, 728,
       730, 732, 734, 736, 738, 740, 742, 744, 746, 748, 750, 752, 754,
       756, 758, 760, 762, 764, 766, 768, 770, 772, 774, 776, 778, 780,
       782, 784, 786, 788, 790, 792, 794, 796, 798, 800, 802, 804, 806,
       808, 810, 812, 814, 816, 818, 820, 822, 824, 826, 828, 830, 832,
       834, 836, 838, 840, 842, 844, 846, 848, 850, 852, 854, 856, 858,
       860, 862, 864, 866, 868, 870, 872, 874, 876, 878, 880, 882, 884,
       886, 888, 890, 892, 894, 896, 898, 900, 902, 904, 906, 908, 910,
       912, 914, 916, 918, 920, 922, 924, 926, 928, 930, 932, 934, 936,
       938, 940, 942, 944, 946, 948, 950, 952, 954, 956, 958, 960, 962,
       964, 966, 968, 970, 972, 974, 976, 978, 980, 982, 984, 986, 988,
       990, 992, 994, 996, 998])

In [10]:
np.arange(2,1000,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208,
       210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234,
       236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260,
       262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286,
       288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312,
       314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338,
       340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 362, 364,
       366, 368, 370, 372, 374, 376, 378, 380, 382, 384, 386, 388, 390,
       392, 394, 396, 398, 400, 402, 404, 406, 408, 410, 412, 414, 416,
       418, 420, 422, 424, 426, 428, 430, 432, 434, 436, 438, 440, 442,
       444, 446, 448, 450, 452, 454, 456, 458, 460, 462, 464, 466, 468,
       470, 472, 474, 476, 478, 480, 482, 484, 486, 488, 490, 492, 494,
       496, 498, 500, 502, 504, 506, 508, 510, 512, 514, 516, 518, 520,
       522, 524, 526, 528, 530, 532, 534, 536, 538, 540, 542, 544, 546,
       548, 550, 552, 554, 556, 558, 560, 562, 564, 566, 568, 570, 572,
       574, 576, 578, 580, 582, 584, 586, 588, 590, 592, 594, 596, 598,
       600, 602, 604, 606, 608, 610, 612, 614, 616, 618, 620, 622, 624,
       626, 628, 630, 632, 634, 636, 638, 640, 642, 644, 646, 648, 650,
       652, 654, 656, 658, 660, 662, 664, 666, 668, 670, 672, 674, 676,
       678, 680, 682, 684, 686, 688, 690, 692, 694, 696, 698, 700, 702,
       704, 706, 708, 710, 712, 714, 716, 718, 720, 722, 724, 726, 728,
       730, 732, 734, 736, 738, 740, 742, 744, 746, 748, 750, 752, 754,
       756, 758, 760, 762, 764, 766, 768, 770, 772, 774, 776, 778, 780,
       782, 784, 786, 788, 790, 792, 794, 796, 798, 800, 802, 804, 806,
       808, 810, 812, 814, 816, 818, 820, 822, 824, 826, 828, 830, 832,
       834, 836, 838, 840, 842, 844, 846, 848, 850, 852, 854, 856, 858,
       860, 862, 864, 866, 868, 870, 872, 874, 876, 878, 880, 882, 884,
       886, 888, 890, 892, 894, 896, 898, 900, 902, 904, 906, 908, 910,
       912, 914, 916, 918, 920, 922, 924, 926, 928, 930, 932, 934, 936,
       938, 940, 942, 944, 946, 948, 950, 952, 954, 956, 958, 960, 962,
       964, 966, 968, 970, 972, 974, 976, 978, 980, 982, 984, 986, 988,
       990, 992, 994, 996, 998])

In [11]:
np.arange(1,71,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70])

In [12]:
np.arange(7,71,7)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [14]:
np.empty((7,7))

array([[             nan,  6.89903272e-310,  5.35567160e-321,
         1.97626258e-323,  4.70350495e-321,  4.76223221e-287,
         4.18967668e-321],
       [ 7.93544645e-301,  2.98415650e-321,  7.93544645e-301,
         4.99994434e-321,  1.34047035e-272,  3.81418679e-321,
         1.69265300e-258],
       [ 5.39519685e-321,  1.29457963e-272,  5.27662110e-321,
         2.49612436e-306,  5.29638372e-321,  1.29620431e-272,
         5.35567160e-321],
       [ 7.53790860e-244,  5.41495948e-321, -7.31469412e-114,
         5.35567160e-321,  3.48014949e-308,  3.47748437e-308,
         4.63524825e-273],
       [ 1.32122555e-228,  1.64643684e-287,  1.29397745e-272,
         1.34065087e-272,  1.63535102e-301,  8.86040129e-220,
         1.29440476e-272],
       [ 2.78137431e-308,  1.63786265e-301,  2.04564941e-277,
         1.29405083e-272,  2.43550680e-209,  3.75833466e-308,
         4.87548614e+127],
       [ 7.26883240e-249,  1.43246684e-277,  7.26883230e-249,
         2.04512008e-277,  4.22972507e-307,  5.83326707e-302,
         1.76150518e-312]])

In [15]:
x=np.ones((20,20))

In [16]:
x.shape

(20, 20)

In [18]:
x.dtype

dtype('float64')

In [19]:
np.ones((5,5),dtype='int32')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [21]:
x.astype('int32')

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [22]:
x.shape

(20, 20)

In [23]:
x.ndim

2

In [24]:
x.reshape((2,2,100))

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1.]]])

In [26]:
x=np.ones((4,5))

In [27]:
x=np.array([7,8,9])

In [28]:
x*5

array([35, 40, 45])

In [29]:
1/x

array([0.14285714, 0.125     , 0.11111111])

In [30]:
import numpy as np
y=np.array([5,9,8])

In [31]:
x*y

array([35, 72, 72])

In [32]:
print(x)
print(y)

[7 8 9]
[5 9 8]

In [33]:
x+y

array([12, 17, 17])

In [34]:
x=np.array([[7,5,8],[6,7,8]])
x

array([[7, 5, 8],
       [6, 7, 8]])

In [35]:
x=np.array([-5,7,8,8,94,3,23])
x>0

array([False,  True,  True,  True,  True,  True,  True])

In [36]:
x[x>0]

array([ 7,  8,  8, 94,  3, 23])

In [37]:
name=np.array(["Naila","Arshan","Nida","xyz","Abc"])

In [38]:
name

array(['Naila', 'Arshan', 'Nida', 'xyz', 'Abc'], dtype='<U6')

In [39]:
marks=np.array([90,60,45,80,15])
marks

array([90, 60, 45, 80, 15])

In [40]:
marks>60

array([ True, False, False,  True, False])

In [41]:
marks[marks>=60]

array([90, 60, 80])

In [42]:
name[marks>=60]

array(['Naila', 'Arshan', 'xyz'], dtype='<U6')

In [43]:
fee=np.array(["submitted","notsubmitted","submitted","notsubmitted","submitted"])

In [44]:
print(fee)
print(name)

['submitted' 'notsubmitted' 'submitted' 'notsubmitted' 'submitted']
['Naila' 'Arshan' 'Nida' 'xyz' 'Abc']

In [45]:
name[fee=="submitted"]

array(['Naila', 'Nida', 'Abc'], dtype='<U6')

In [46]:
name[0]

'Naila'

In [48]:
print(name)
name[0:3]

['Naila' 'Arshan' 'Nida' 'xyz' 'Abc']

array(['Naila', 'Arshan', 'Nida'], dtype='<U6')

In [49]:
x=np.zeros((10,10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [50]:
x[0,:]=1

In [51]:
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [52]:
x[-1,:]=1
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [53]:
x[::,0]=1
x[:,-1]=1
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [54]:
x=np.ones((10,10))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [55]:
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [56]:
x=np.ones((10,10))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [57]:
x=np.ones((10,10)) #footBall ground

x[1::2,:]=0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [58]:
x=np.ones((10,10)) # checkers board
x[:11:2,0:11:2]=0
x[1:11:2,1:11:2]=0
x

array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.]])